### ISSUE TITLE
Still active - collaboration?

### ISSUE THREAD

**Issue by astronomyk** [bmorris3/telescopy#2]
Hi Brett,

we met at .astronomy in Sydney several years ago. I was the bloke with the attempt at a Lego telescope. Probably not that memorable though ;)

Anyway I was just wondering whether this project is still active, as I've been working on a similar package - originally named Telescopy, now renamed to [ScopeSim](https://github.com/astronomyk/ScopeSim). It's goal is to be a generic platform for simulating detector outputs for the range of instruments and telescope in ESOs arsenal.

Anyway, I just thought I'd reach out to you in case anyone is still actively working on this project to see if there's any way for us to avoid reinventing the wheel. I'd love to turn my project into an astropy affiliated package, but I just haven't found the time to go that route yet.

Cheers,
Kieran

**Comment by bmorris3** [comment]
Hi Kieran,  

Great to hear from you again! I'm currently working with Google Summer of Code student @tcjansen on a replacement for my telescopy package which will probably live within the `synphot` and `astroplan` projects. To see what Tiffany has been up to, take a peek at her blog: https://astrotiff.home.blog

**Comment by astronomyk** [comment]
Hi Brett,

thanks for the link. I had a quick skim through her blog and saw the tynt package. I think I'll be building that into scopesim (with appropriate citations of course :). 

In a similar vein, and related to Tiffany's work with skycalc_cli, I created a tiny package a while ago ([skycalc_ipy](https://skycalc-ipy.readthedocs.io/en/latest/)) which queries ESO's Skycalc tool and returns a spectrum in a variety of formats (synphot.SourceSpectrum, astropy.Table, fits.BinTable, numpy.array etc). I could imagine it being of use for the specphot project, but then again it might not be. Who knows. 

Btw, will you be ad ADASS? If so we should probably grab a beer at some point.

Cheers,
Kieran

**Comment by bmorris3** [comment]
Awesome, I'll be sure to share that project with Tiffany.

Let me know if I can make `tynt` more useful for you!

I don't plan to be at ADASS, but who knows. 😄

**Comment by astronomyk** [comment]
Thanks! 
I'll let you know about tynt when I get around to playing with it properly!
Cheers
